### PR TITLE
Make clear that LXDE is still alive

### PR DESCRIPTION
**Pull request by jubalh**
Fixes https://github.com/lxde/lxde.github.io/issues/24

### CODE REVIEW

**Comment by paulolieuthier** [comment]
I think the original text keeps 80 characters width.

**Comment by pmattern** [comment]
True, but I wonder whether we should really insist on this.
It's Markdown after all so the line breaks don't really matter anyway. IMO it's adequate to use flowed regular text as this makes editing much easier but doesn't introduce any downside as far as the result is concerned.

**Comment by paulolieuthier** [comment]
As long as we are consistent. But I actually agree.

**Comment by jubalh** [comment]
I think that breaking lines for visual purposes is a thing the editor should do not hand formatted. But yes it should be consistent.
I will change it as soon as you guys tell me if you prefer commit 1 or 2 ;)

**Comment by luis-pereira** [comment]
Never payed much attention to this. But I definitly prefer the the "alternative" version.
Stating that LXQt is the Qt port of LXDE and in the next sentence stating that it is the merge of LXDE-Qt and razor-qt, contradicts the first sentence.

LXQt is really the merge of LXDE-Qt and razor-qt.

**Pull request merged**
