### PR TITLE
Fix Typos

### PR DESCRIPTION
**Pull request by nothingneko**
I left two typos in the features section, this MR fixes them, I am sorry.

### CODE REVIEW

**Comment by jubalh** [comment]
Can you squash the two commits into one?

**Comment by nothingneko** [comment]
It's not letting me

**Comment by jubalh** [comment]
`git rebase -i HEAD~2`, `git push -f`

**Comment by nothingneko** [comment]
I did that and it said everything up to date already. I'm not sure what else to do here

**Comment by jubalh** [comment]
`git rebase -i HEAD~2` will open a window. there you need to put a `s` for squash into the 2nd commit line

**Comment by nothingneko** [comment]
I'm sorry they're unverified something's wrong on my end, I don't use Git CLI all too often

**Comment by jubalh** [comment]
From 2 commits I wanted to have 1. Now we have 4 :)

**Comment by nothingneko** [comment]
I'm not sure what to do here honestly

**Comment by jubalh** [comment]
I did it for you.

**Comment by nothingneko** [comment]
Thank you!

**Pull request merged**
